check50: 

  files:
    - !exclude '*'
    - !include '*.c'
    - !require 'hello.c'

  checks:
    responds to Brian:
      - run: clang hello.c -o hello -lcs50
        exit: 0
      - run: ./hello
        stdin: "Brian"
        stdout: "hello, Brian\n"
        exit: 0
    responds to Alex:
      - run: clang hello.c -o hello -lcs50
        exit: 0
      - run: ./hello
        stdin: "Alex"
        stdout: "hello, Alex\n"
        exit: 0
